# Generated by Django 5.1.5 on 2025-05-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionuserdetails',
            name='guest',
        ),
    ]
