# Generated by Django 5.1.5 on 2025-05-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_payment_tax_amount_payment_tax_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
