# Generated by Django 5.1.5 on 2025-05-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_payment_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='is_platform_fee',
            field=models.BooleanField(default=False),
        ),
    ]
