# Generated by Django 5.1.4 on 2024-12-31 04:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(upload_to='room_images/%Y/%m/%d/'),
        ),
    ]
