# Generated by Django 5.1.4 on 2025-01-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_roomimage_uploaded_at_alter_roomimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_dashboard', 'Can view dashboard')]},
        ),
        migrations.AlterField(
            model_name='guest',
            name='proof_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('pan', 'Pan Card'), ('aadhar', 'Aadhar Card')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='hotelapp_customuser',
        ),
    ]
