# Generated by Django 5.1.5 on 2025-05-13 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_tax'),
        ('subscription', '0008_tax_is_platform_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='subscription_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.subscriptionuserdetails'),
        ),
    ]
