# Generated by Django 5.1.4 on 2025-01-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0004_alter_customuser_options_alter_guest_proof_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('staff', 'Staff'), ('admin', 'Admin')], default='admin', max_length=10),
        ),
    ]
