# Generated by Django 5.1.4 on 2025-01-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reset_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
