# Generated by Django 5.1.5 on 2025-05-05 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermap',
            name='subscription_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_map', to='subscription.subscriptionuserdetails'),
        ),
    ]
